### ISSUE TITLE
Leap year tests crash

### ISSUE THREAD

**Issue by SuddenGunter** [exercism/erlang-test-runner#97]
My code seems to be fine, but tests crash when running it

Code:
```erlang
-module(leap).

-export([leap_year/1]).

leap_year(_Year) when _Year rem 400 == 0 -> true.
leap_year(_Year) when _Year rem 100 == 0 -> false.
leap_year(_Year) when _Year rem 4 == 0  -> true.
leap_year(_Year) -> false.
```
Info from test report
```
{"/mnt/exercism-iteration/src/leap.erl",
          [{{6,
          1},
   erl_lint,
     {redefine_function,
   {leap_year,
       1}}},
         {{7,
   1},
  erl_lint,
  {redefine_function,
  {leap_year,
  1}}},
{{8,
1},
   erl_lint,
{redefine_function,
  {leap_year, 1}}}]}.
 ```

**Comment by NobbZ** [comment]
Your code is wrong. You have to use the semicolon (`;`) to seperate the clauses. Only the last one gets the dot (`.`).

**Comment by SuddenGunter** [comment]
yeap, my bad :)
fixed it later

error reporting for Erlang might be improved a bit, though; where the code is invalid, it says to report an issue instead of giving a stdout of the compiler. Would it be possible to add at least some error reporting?

**Comment by NobbZ** [comment]
Are you solving this on the web-editor?

In that case, yes, the test runner is rather limited and I have not yet managed to improve it in that regard. I'd be happy if you could open a ticket in the [test runners](https://github.com/exercism/erlang-test-runner) repo, such that I have some work item to remember to tackle eventually ;)
